# Generated by Django 4.1.4 on 2023-05-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_image'),
        ),
    ]
